version: '3'
services:
  database:
    image: postgres:13.1
    container_name: database
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - bookshelf

  app:
    container_name: bookshelf
    image: simple-nestjs-api
    ports:
      - '3001:3000'
    volumes:
      - myvols:/usr/src/app
    environment:
      NODE_ENV: production
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    restart: always
    networks:
      - bookshelf

networks:
  bookshelf:

volumes:
  myvols: