---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.volume.name }}
  labels:
    type: local
spec:
  storageClassName: nfs-client
  capacity:
    storage: {{ .Values.postgres.volume.size }}
  accessModes:
    - {{ .Values.postgres.pvc.accessModes}}
  hostPath:
    path: /data/db