---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.pvc.name }}
spec:
  storageClassName: nfs-client
  accessModes:
  - {{ .Values.postgres.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage }}