---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secret.name }}
  labels:
    app: {{ .Values.postgres.name }}
    group: {{ .Values.postgres.group }}
type: Opaque
data:
  DB_USER: {{ .Values.postgres.secret.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgres.secret.password | b64enc | quote }}
  DB_NAME: {{ .Values.postgres.secret.db_name | b64enc | quote }}