apiVersion: v1
kind: Secret
metadata:
  name: bookshelf-db-secret
type: Opaque
stringData:
  DB_PORT: "5432"
data:
  DB_USER: {{ .Values.secret.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secret.password | b64enc | quote }}
  DB_NAME: {{ .Values.postgres.secret.db_name | b64enc | quote }}